# Generated by Django 5.2.5 on 2025-08-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0003_rename_body_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='body',
        ),
    ]
